name: CI
on:
  push:
    branches:
      - test-ci
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 24
          - 22
          - 20
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: nproc
      - run: lscpu
      - run: npm install
      - run: |
          npm run test:tsc & pid_tsc=$!
          npm run test:tsd & pid_tsd=$!
          npm run test:xo & pid_xo=$!
          npm run test:linter & pid_linter=$!
          wait $pid_tsc && wait $pid_tsd && wait $pid_xo && wait $pid_linter
  types:
    name: TypeScript ${{ matrix.typescript-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        typescript-version:
          - 'latest'
          - '~6.0.0'
          - '~5.9.0'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install
      - run: npm install typescript@${{ matrix.typescript-version }} --legacy-peer-deps
      - run: NODE_OPTIONS="--max-old-space-size=6144" npx tsc
